---
version: "3"
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:stable
    image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    # ports:
    #   - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy UptrendStrategy
    # --strategy UptrendRetraceStrategy
    # -strategy AOTSStrategy
    # --strategy BBRSINaiveStrategy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - nodes.role == manager

      restart_policy:
        condition: on-failure
        delay: 5s

      # labels:
    # Pairlist
    # "method": "StaticPairList",
    # Not llowed for backtesting: VolumePairList, AgeFilter
    # ['StaticPairList', 'VolumePairList', 'AgeFilter', 'OffsetFilter', 'PerformanceFilter',
    # 'PrecisionFilter', 'PriceFilter', 'RangeStabilityFilter', 'ShuffleFilter', 'SpreadFilter', 'VolatilityFilter']
    # docker-compose run --rm freqtrade hyperopt --hyperopt-loss SharpeHyperOptLossDaily --spaces all --ignore-missing-spaces --strategy UptrendStrategy -e 1000
    # docker-compose run --rm freqtrade hyperopt --hyperopt-loss SharpeHyperOptLossDaily --spaces all --ignore-missing-spaces --strategy UptrendStrategy -e 1000 --eps
    # docker-compose run --rm freqtrade backtesting -c user_data/config.json -s UptrendStrategy --timeframe 15m
    # docker-compose run --rm freqtrade plot-dataframe -c user_data/config.json -p SHIB/USDT --timeframe 15m

    # --hyperopt-loss NAME, --hyperoptloss NAME
    #                     shorttradedurhyperoptloss, onlyprofithyperoptloss,
    #                     sharpehyperoptloss, sharpehyperoptlossdaily,
    #                     sortinohyperoptloss, sortinohyperoptlossdaily,
    #
    # # --spaces {all,buy,sell,roi,stoploss,trailing,protection,default}
    # --eps, --enable-position-stacking
    #                     Allow buying the same pair multiple times (position
    #                     stacking).
